### ISSUE TITLE
Delete offensive detections from child rooms after a minute

### ISSUE THREAD

**Issue by superplane39** [thesecretmaster/ips-comment-bot#10]
It's probably best not to leave the offensive content in child rooms for long. (This caused an argument in The Closet a bit back.)

If the bot deleted the messages about the offensive detection a minute (or possibly a minute and a half) after reporting, that's long enough for it to be seen and have action taken on it, but within the time limit for deleting your own chat messages.

**Comment by spacemonaut** [comment]
Alternately: if the comment matches the Offensive flag, don't post it at all in the first place, just link to it.

**Comment by thesecretmaster** [comment]
@spacemonaut That'd be a bit easier to do. I think I'll try to do both.
