### ISSUE TITLE
Alert HQ room when a user passes a threshold of tp comments

### ISSUE THREAD

**Issue by superplane39** [thesecretmaster/ips-comment-bot#20]
It'd be nice to have a warning when a user has been leaving a lot of delete-worthy comments.

I'm thinking a message in the HQ room every time someone passes multiples of 20 tp comments.

E.g.:

`**Alert**: User <ID> has left 40 comments marked tp. (@Mithrandir)`

This would happen at 20, 40, 60, 80...

This would be without using the username, just the ID.

**Comment by scohe001** [comment]
This would be a pretty simple query after anyone marks a comment tp. I could do it, but only with @thesecretmaster's blessing...

**Comment by thesecretmaster** [comment]
https://chat.stackexchange.com/transcript/63296?m=47031354#47031354

> @Mithrandir Saw your FR. I don't love the idea because we're supposed look at content and not users. If/when a web dashboard exists, it's definitely something I'd add as a mod-only feature. However, I'm not sure if it's a good idea to give everyone access to that list.

**Comment by scohe001** [comment]
Closing this as we've decided we're not going to go through with implementing it.
