### ISSUE TITLE
Link feedbacks to people

### ISSUE THREAD

**Issue by thesecretmaster** [thesecretmaster/ips-comment-bot#28]
This would just be a handy thing to have. Also we should maybe add some logging around feedback time, location, and the original regexes that caught it. I may go in and do this myself when I get time.

**Comment by scohe001** [comment]
I'm going to leave off logging regexes, since especially now that we have so many Closet lurkers, many comments get feedbacks even though they weren't caught on anything.

I do like the idea of including a room_id with the info though so we can analyze where things are happening. Good call.

**Comment by scohe001** [comment]
Completed as of https://github.com/thesecretmaster/ips-comment-bot/pull/43
