### ISSUE TITLE
"Huh?" functionality broken for Toxicity

### ISSUE THREAD

**Issue by scohe001** [thesecretmaster/ips-comment-bot#30]
It looks like "huh?" doesn't report "high toxicity" even if the toxicity is >= to .7.

Here is the line that should be reporting it: https://github.com/thesecretmaster/ips-comment-bot/blob/master/comment_scan.rb#L111

And here is an example of it failing: https://chat.stackexchange.com/transcript/message/50545563#50545563

This is probably something silly, but I'm writing up an issue so I'll remember to poke at it when I have the time.

**Comment by thesecretmaster** [comment]
Fixed in https://github.com/thesecretmaster/ips-comment-bot/commit/d19bb047c0feee1664cc919dfe08d14e0bfc4a02
