### ISSUE TITLE
Add unit tests (that GitHub will auto-trigger when pushing new code)

### ISSUE THREAD

**Issue by scohe001** [thesecretmaster/ips-comment-bot#34]
This is maybe more of a longterm goal, but it'd be really awesome if we could get some unit tests in the project. Bonus points if we could get them to auto-run when someone tries to make a pull request (to make it easy to see if there are build errors/obvious semantic errors that break stuff).

This'd probably require a pretty big refactor to make the core functions callable from a test with test data. We'd have to add a level of abstraction so that we can fake the SE API calls.

I definitely won't be trying this any time soon, but maybe some day...

**Comment by thesecretmaster** [comment]
Yes, definitely. This would be a good thing, however I think it might require changes to some dependencies (i.e. ChatX, SE::API). It'd be a big project, although it would be useful.

**Comment by scohe001** [comment]
@thesecretmaster 

So I actually got kinda fired up about this this weekend and started on a *major* refactor that would isolate the dependencies to make it easy to make mock classes. I also set things up to use a test_db for when the unit-tests get run (that'll get wiped before/after every test module).

I pushed it up in [the unit-test branch](https://github.com/thesecretmaster/ips-comment-bot/commit/5e8407f3ffa767aa15783c55a39e307bc22bc54d).

As this is a friggin massive overhaul, I think it'd probably be a good idea if you took a look at it to give me the greenlight that I'm on the right track, before I put more work into it and end up having to scrap everything.

From here I'll probably continue much the same with a wrapper for handling chat replies and then another for the SE client.

Let me know what you think when you get the chance.

**Comment by thesecretmaster** [comment]
Couple of things: Firstly, delete code instead of commenting it -- it's all stored in the git history, we don't need it anymore. Second, you don't need a main function. Just put it in the top level scope. Third, is this tested? Do you know it all runs fine? (this is just initial thoughts, I haven't really reviewed the substance yet)

**Comment by thesecretmaster** [comment]
Also, can you make it a PR? I need it to be a PR so I can actually leave comments, otherwise github won't let me.

**Comment by scohe001** [comment]
Firstly. Good call. I guess old habits die hard. I've been cleaning it up as I recreate it, but I'll kill it all on my next commit.

Secondly, old habits die hard pt. II, I'll take it out.

Thirdly, I've been testing as I'm going by hand, but I'm also slowly adding tests too. By the time I finish I should have basic tests for most of it. (But suffice to say it is functional--or what I've made so far is).

Lastly, I'm going to hold out until I have a fully working version to make a pull request (which should be the end of this weekend). I'll give you a ping when I do.

**Comment by scohe001** [comment]
The big refactor is here!! Merged into master as of [147fa43bca23f2ae19ee80cee6c2ecb393bda9a5](https://github.com/thesecretmaster/ips-comment-bot/commit/147fa43bca23f2ae19ee80cee6c2ecb393bda9a5)

**Comment by scohe001** [comment]
Github auto-triggers test runs on push as of https://github.com/thesecretmaster/ips-comment-bot/commit/be23595807a08196211c0c2a4d16803be281e5b8!!
