### ISSUE TITLE
[FR] Adding command !!/cats to display random picture of cat

### ISSUE THREAD

**Issue by AElisDesBois** [thesecretmaster/ips-comment-bot#38]
As discussed in chat (https://chat.stackexchange.com/transcript/message/51960200#51960200) it would be nice to have a bot displaying (cute) pictures of cats when we ask for it.

This API can be used: aws.random.cat/meow

The proposed command could be `!!/cats`

(this shouldn't be implemented on the meta bot to avoid having to bots responding to this same command)

**Comment by scohe001** [comment]
Note: meta bot doesn't live in TAS like the main bot does, so I don't think we'll need to put any special code in place to prevent meta from having this.

**Comment by AElisDesBois** [comment]
@scohe001 I was more thinking about me (or someone else), using The Closet to be flooded by cats, but if someone really wants to be flooded by cats, having two bots answering instead of one isn't an issue I suppose ^^

**Comment by scohe001** [comment]
Also, it'd be cool if we could make this happen with any mention of IPSCommentBot that contains the word "Cat" in the message. Then we could do things like:

> @IPSCommentBot I'm sad, give me a cat.

Or when replying to a comment post

> @IPSCommentBot this comment sucks. Give them a cat.

We only deal with message replies at the moment though, not mentions. So this might be a little work (but worth it!).

**Comment by AElisDesBois** [comment]
If we do a "cat" trigger (which would be super-cool!), it would be nice to also have it triggered by the word "kitty" or "kitten"

**Comment by scohe001** [comment]
Since dream.io jpg's and gif's (the files returned by that endpoint) onebox in chat, it should be as easy as posting the string returned by this to chat (hopefully with some checks for bad responses, but this is the gist):

    HTTParty.post("https://aws.random.cat/meow").parsed_response.first[1]

It'd be a pretty easy change, but as this doesn't have a whole lot to do with comment scanning and moderation, I'd like a green light from @thesecretmaster before implementing.

**Comment by thesecretmaster** [comment]
Green light-ed! Fun is good!

**Comment by scohe001** [comment]
This is implemented as of [d70adc3a698c1fc2ebe1ab6bd5d6a7b993ba2743](https://github.com/thesecretmaster/ips-comment-bot/commit/d70adc3a698c1fc2ebe1ab6bd5d6a7b993ba2743#diff-99020da1b9beab4c65a84371ad896dc5R142-R146).
