### ISSUE TITLE
Add some gamification to encourage more feedbacks

### ISSUE THREAD

**Issue by scohe001** [thesecretmaster/ips-comment-bot#42]
<sup> Normally, I'd just implement this, but I'm not sure if this is a direction we want to take the bot. I'm posting this here to get my thoughts down and have something to point TAS users to.</sup>

With the (near) completion of https://github.com/thesecretmaster/ips-comment-bot/issues/28, we'll have each new feedback (tp/fp/rude) linked to a chat user. I propose we add some soft gamification in TAS to encourage more feedbacks. This plan has two parts:

1. On feedback (tp/fp/rude) given, check the total number of feedbacks attributed to that user. Print a congratulatory message (instead of the usual message) if they've reached a milestone. ie...
  a. "Congratulations on your first feedback, `@user`! Now feed me moooaaaare :D"
  b. "Let's all give `@user` a pat on the back for their 25th feedback!"
  c. "Holy moly did you really just give me your 100th feedback, `@user`?!"

2. Create a scoreboard mention command (similar to cats, ie: "`@ips`, gimme teh scoreboard"). This command will show the top 10 users with the most feedbacks in a table like
`User | XXX Total | YYY tp's | ZZZ fp's`

However, I'm not sure if this is something we want to do. I'll run it by TAS now that it's written up and see what they say.

**Comment by AElisDesBois** [comment]
Maybe only give a point if you are the first to give the feedback?

Also, I'm kind of afraid of new people given wrong feedbacks before they figure things out (like the fact that you should use "tp" even if the catch doesn't match). Maybe give them a link to some explaination if it's the first time they are reporting a comment?

**Comment by scohe001** [comment]
Hmm I think I'm kinda against "rewarding" only the first feedback. Not only because it would require more work technically, but because more data points are just as useful. I don't think we should discourage feedbacks just because there already are some.

I like the idea of giving a link to some help for the first time, but I feel like with all the ppl who are always in chat, it would probably just be extra noise. In fact, [just yesterday](https://chat.stackexchange.com/transcript/message/52329529#52329529) someone had like 4 people telling them how the bot worked after asking one question :p

**Comment by thesecretmaster** [comment]
I think gamification could be good but a) all feedback should be rewarded equally and b) there should be a way to invalidate incorrect feedback. This could be done by either "trusted users" or mods.

**Comment by scohe001** [comment]
I'm adding a feature to only allow one user one feedback per comment. So if you try to apply a different feedback than you had originally, it'll clear the first feedback and apply the second. If you try to re-apply a feedback you already gave, it'll clear that feedback.

So users have a way to clear their own. But I'm not sure how we'd implement other ppl clearing. I guess we could use the whitelisted user list + mods, but how would that work technically? Reply to the feedback message (`@ips tp`) with "BAD"? (not sure we'd want everyone to see that).

**Comment by thesecretmaster** [comment]
If there's a web ui on the roadmap, invalidation could go there, or just an API+userscript.

**Comment by AElisDesBois** [comment]
Maybe we don't really need to invalidate someone else feedback if we have the information that the comment was both marked as tp and fp?

**Comment by thesecretmaster** [comment]
I'm thinking of invalidation as a "this is clearly incorrect and any sane human would think so", which is a higher standard than just disagreement.

**Comment by AElisDesBois** [comment]
"this is clearly incorrect and any sane human would think so" x) 
In this case, I think a "@ips tp" with the keyword "invalid"/"invalidate" would do (no need to scream "BAD" IMO ^^)

**Comment by scohe001** [comment]
Sounds like this isn't worth the dev time from the feedback both here and in TAS. Closing and declining it for now.
