### ISSUE TITLE
Don't duplicate post manually reported comments

### ISSUE THREAD

**Issue by Rainbacon** [thesecretmaster/ips-comment-bot#44]
When a user manually reports a comment, it gets reposted in every chat room that the bot is in, including the room it was reported from. It can be a little confusing seeing the same comment posted twice, so I propose that the bot not repost manually reported comments in the room they were reported from.

**Comment by scohe001** [comment]
Should be pretty straightforward. Could do it by passing around the room_id not to post to with the report flag, but I think the easiest way will be locking report capability down to the hq room only (which I probably should've done from the beginning). Then it'll just be an extra condition in the report_comment logic in Scanner when posting to hq.

Would also be helpful to add some kind of "Comment reported successfully" message to hq after the report logic has run (this'll be in the Replier).

**Comment by scohe001** [comment]
Completed as of https://github.com/thesecretmaster/ips-comment-bot/pull/43
