### ISSUE TITLE
Have a "x comments in time y on post z" alert

### ISSUE THREAD

**Issue by superplane39** [thesecretmaster/ips-comment-bot#5]
What would be useful for identifying problematic comment threads would be a certain amount of comments in a certain timeframe triggering a message from the bot to the chatroom.

For instance, 10 comments in 5 minutes, 20 comments in an hour, 30 in the past day, on the past day.

Such a message would probably look like

> Possible argument: 10 comments in 5 minutes on post [Title]() by [user]().

Posted in both the control and child rooms.

**Comment by thesecretmaster** [comment]
Implementation would have to be first storing post_id in the DB with comment ID and doing a DB query each time a new comment comes looking for comments with post_id in the last N minutes.

**Comment by scohe001** [comment]
Resolved as of https://github.com/thesecretmaster/ips-comment-bot/pull/43
